services:
  postgres:
    image: postgres:18.3
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wedsitedb
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  wedsite:
    image: wedsite:latest
    build:
      context: .
      dockerfile: Dockerfile.dockerignore
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
volumes:
  postgres_data: