spring.application.name=wedsite
#Datasource configuration
spring.datasource.url=jdbc:postgresql://pooler-supabase-co-db.napfbtxjeilnwyhiwunx.supabase.co:5432/postgres?sslmode=require&stringtype=unspecified
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# === HikariCP  ===
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
