spring.application.name=wedsite
#Datasource configuration
spring.datasource.url=jdbc:postgresql://pooler-supabase-co-db.napfbtxjeilnwyhiwunx.supabase.co:5432/postgres?sslmode=require&stringtype=unspecified
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
